/* soapH.h
   Generated by gSOAP 2.8.22 from demo.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_float(soap, data), 0) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_double(soap, data), 0) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_demo__AddC
#define SOAP_TYPE_demo__AddC (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__AddC(struct soap*, struct demo__AddC *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__AddC(struct soap*, const struct demo__AddC *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__AddC(struct soap*, const char*, int, const struct demo__AddC *, const char*);
SOAP_FMAC3 struct demo__AddC * SOAP_FMAC4 soap_in_demo__AddC(struct soap*, const char*, struct demo__AddC *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__AddC(struct soap*, const struct demo__AddC *, const char*, const char*);

#ifndef soap_write_demo__AddC
#define soap_write_demo__AddC(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__AddC(soap, data), 0) || soap_put_demo__AddC(soap, data, "demo:AddC", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddC * SOAP_FMAC4 soap_get_demo__AddC(struct soap*, struct demo__AddC *, const char*, const char*);

#ifndef soap_read_demo__AddC
#define soap_read_demo__AddC(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__AddC(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__AddC * SOAP_FMAC2 soap_instantiate_demo__AddC(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__AddC * soap_new_demo__AddC(struct soap *soap, int n = -1) { return soap_instantiate_demo__AddC(soap, n, NULL, NULL, NULL); }

inline struct demo__AddC * soap_new_req_demo__AddC(struct soap *soap) { struct demo__AddC *_p = soap_instantiate_demo__AddC(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddC(soap, _p); } return _p; }

inline struct demo__AddC * soap_new_set_demo__AddC(struct soap *soap, void *_) { struct demo__AddC *_p = soap_instantiate_demo__AddC(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddC(soap, _p); _p->_ = _; } return _p; }

inline void soap_delete_demo__AddC(struct soap *soap, struct demo__AddC *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__AddC(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_demo__AddB
#define SOAP_TYPE_demo__AddB (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__AddB(struct soap*, struct demo__AddB *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__AddB(struct soap*, const struct demo__AddB *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__AddB(struct soap*, const char*, int, const struct demo__AddB *, const char*);
SOAP_FMAC3 struct demo__AddB * SOAP_FMAC4 soap_in_demo__AddB(struct soap*, const char*, struct demo__AddB *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__AddB(struct soap*, const struct demo__AddB *, const char*, const char*);

#ifndef soap_write_demo__AddB
#define soap_write_demo__AddB(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__AddB(soap, data), 0) || soap_put_demo__AddB(soap, data, "demo:AddB", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddB * SOAP_FMAC4 soap_get_demo__AddB(struct soap*, struct demo__AddB *, const char*, const char*);

#ifndef soap_read_demo__AddB
#define soap_read_demo__AddB(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__AddB(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__AddB * SOAP_FMAC2 soap_instantiate_demo__AddB(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__AddB * soap_new_demo__AddB(struct soap *soap, int n = -1) { return soap_instantiate_demo__AddB(soap, n, NULL, NULL, NULL); }

inline struct demo__AddB * soap_new_req_demo__AddB(struct soap *soap, double a, double b) { struct demo__AddB *_p = soap_instantiate_demo__AddB(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddB(soap, _p); _p->a = a; _p->b = b; } return _p; }

inline struct demo__AddB * soap_new_set_demo__AddB(struct soap *soap, double a, double b) { struct demo__AddB *_p = soap_instantiate_demo__AddB(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddB(soap, _p); _p->a = a; _p->b = b; } return _p; }

inline void soap_delete_demo__AddB(struct soap *soap, struct demo__AddB *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__AddB(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_demo__AddA
#define SOAP_TYPE_demo__AddA (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__AddA(struct soap*, struct demo__AddA *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__AddA(struct soap*, const struct demo__AddA *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__AddA(struct soap*, const char*, int, const struct demo__AddA *, const char*);
SOAP_FMAC3 struct demo__AddA * SOAP_FMAC4 soap_in_demo__AddA(struct soap*, const char*, struct demo__AddA *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__AddA(struct soap*, const struct demo__AddA *, const char*, const char*);

#ifndef soap_write_demo__AddA
#define soap_write_demo__AddA(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__AddA(soap, data), 0) || soap_put_demo__AddA(soap, data, "demo:AddA", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddA * SOAP_FMAC4 soap_get_demo__AddA(struct soap*, struct demo__AddA *, const char*, const char*);

#ifndef soap_read_demo__AddA
#define soap_read_demo__AddA(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__AddA(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__AddA * SOAP_FMAC2 soap_instantiate_demo__AddA(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__AddA * soap_new_demo__AddA(struct soap *soap, int n = -1) { return soap_instantiate_demo__AddA(soap, n, NULL, NULL, NULL); }

inline struct demo__AddA * soap_new_req_demo__AddA(struct soap *soap, double a, double b) { struct demo__AddA *_p = soap_instantiate_demo__AddA(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddA(soap, _p); _p->a = a; _p->b = b; } return _p; }

inline struct demo__AddA * soap_new_set_demo__AddA(struct soap *soap, double a, double b) { struct demo__AddA *_p = soap_instantiate_demo__AddA(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddA(soap, _p); _p->a = a; _p->b = b; } return _p; }

inline void soap_delete_demo__AddA(struct soap *soap, struct demo__AddA *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__AddA(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_demo__AddAResponse
#define SOAP_TYPE_demo__AddAResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__AddAResponse(struct soap*, struct demo__AddAResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__AddAResponse(struct soap*, const struct demo__AddAResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__AddAResponse(struct soap*, const char*, int, const struct demo__AddAResponse *, const char*);
SOAP_FMAC3 struct demo__AddAResponse * SOAP_FMAC4 soap_in_demo__AddAResponse(struct soap*, const char*, struct demo__AddAResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__AddAResponse(struct soap*, const struct demo__AddAResponse *, const char*, const char*);

#ifndef soap_write_demo__AddAResponse
#define soap_write_demo__AddAResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__AddAResponse(soap, data), 0) || soap_put_demo__AddAResponse(soap, data, "demo:AddAResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddAResponse * SOAP_FMAC4 soap_get_demo__AddAResponse(struct soap*, struct demo__AddAResponse *, const char*, const char*);

#ifndef soap_read_demo__AddAResponse
#define soap_read_demo__AddAResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__AddAResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__AddAResponse * SOAP_FMAC2 soap_instantiate_demo__AddAResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__AddAResponse * soap_new_demo__AddAResponse(struct soap *soap, int n = -1) { return soap_instantiate_demo__AddAResponse(soap, n, NULL, NULL, NULL); }

inline struct demo__AddAResponse * soap_new_req_demo__AddAResponse(struct soap *soap, double res) { struct demo__AddAResponse *_p = soap_instantiate_demo__AddAResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddAResponse(soap, _p); _p->res = res; } return _p; }

inline struct demo__AddAResponse * soap_new_set_demo__AddAResponse(struct soap *soap, double res) { struct demo__AddAResponse *_p = soap_instantiate_demo__AddAResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddAResponse(soap, _p); _p->res = res; } return _p; }

inline void soap_delete_demo__AddAResponse(struct soap *soap, struct demo__AddAResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__AddAResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_demo__AddBResponse
#define SOAP_TYPE_demo__AddBResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__AddBResponse(struct soap*, struct demo__AddBResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__AddBResponse(struct soap*, const struct demo__AddBResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__AddBResponse(struct soap*, const char*, int, const struct demo__AddBResponse *, const char*);
SOAP_FMAC3 struct demo__AddBResponse * SOAP_FMAC4 soap_in_demo__AddBResponse(struct soap*, const char*, struct demo__AddBResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__AddBResponse(struct soap*, const struct demo__AddBResponse *, const char*, const char*);

#ifndef soap_write_demo__AddBResponse
#define soap_write_demo__AddBResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__AddBResponse(soap, data), 0) || soap_put_demo__AddBResponse(soap, data, "demo:AddBResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddBResponse * SOAP_FMAC4 soap_get_demo__AddBResponse(struct soap*, struct demo__AddBResponse *, const char*, const char*);

#ifndef soap_read_demo__AddBResponse
#define soap_read_demo__AddBResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__AddBResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__AddBResponse * SOAP_FMAC2 soap_instantiate_demo__AddBResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__AddBResponse * soap_new_demo__AddBResponse(struct soap *soap, int n = -1) { return soap_instantiate_demo__AddBResponse(soap, n, NULL, NULL, NULL); }

inline struct demo__AddBResponse * soap_new_req_demo__AddBResponse(struct soap *soap) { struct demo__AddBResponse *_p = soap_instantiate_demo__AddBResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddBResponse(soap, _p); } return _p; }

inline struct demo__AddBResponse * soap_new_set_demo__AddBResponse(struct soap *soap) { struct demo__AddBResponse *_p = soap_instantiate_demo__AddBResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__AddBResponse(soap, _p); } return _p; }

inline void soap_delete_demo__AddBResponse(struct soap *soap, struct demo__AddBResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__AddBResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_demo__Result
#define SOAP_TYPE_demo__Result (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_demo__Result(struct soap*, struct demo__Result *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_demo__Result(struct soap*, const struct demo__Result *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_demo__Result(struct soap*, const char*, int, const struct demo__Result *, const char*);
SOAP_FMAC3 struct demo__Result * SOAP_FMAC4 soap_in_demo__Result(struct soap*, const char*, struct demo__Result *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_demo__Result(struct soap*, const struct demo__Result *, const char*, const char*);

#ifndef soap_write_demo__Result
#define soap_write_demo__Result(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_demo__Result(soap, data), 0) || soap_put_demo__Result(soap, data, "demo:Result", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__Result * SOAP_FMAC4 soap_get_demo__Result(struct soap*, struct demo__Result *, const char*, const char*);

#ifndef soap_read_demo__Result
#define soap_read_demo__Result(soap, data) ( soap_begin_recv(soap) || !soap_get_demo__Result(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct demo__Result * SOAP_FMAC2 soap_instantiate_demo__Result(struct soap*, int, const char*, const char*, size_t*);

inline struct demo__Result * soap_new_demo__Result(struct soap *soap, int n = -1) { return soap_instantiate_demo__Result(soap, n, NULL, NULL, NULL); }

inline struct demo__Result * soap_new_req_demo__Result(struct soap *soap, float a, float b, float res) { struct demo__Result *_p = soap_instantiate_demo__Result(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__Result(soap, _p); _p->a = a; _p->b = b; _p->res = res; } return _p; }

inline struct demo__Result * soap_new_set_demo__Result(struct soap *soap, float a, float b, float res) { struct demo__Result *_p = soap_instantiate_demo__Result(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_demo__Result(soap, _p); _p->a = a; _p->b = b; _p->res = res; } return _p; }

inline void soap_delete_demo__Result(struct soap *soap, struct demo__Result *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_demo__Result(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTodemo__Result
#define SOAP_TYPE_PointerTodemo__Result (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTodemo__Result(struct soap*, struct demo__Result *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTodemo__Result(struct soap*, const char *, int, struct demo__Result *const*, const char *);
SOAP_FMAC3 struct demo__Result ** SOAP_FMAC4 soap_in_PointerTodemo__Result(struct soap*, const char*, struct demo__Result **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTodemo__Result(struct soap*, struct demo__Result *const*, const char*, const char*);

#ifndef soap_write_PointerTodemo__Result
#define soap_write_PointerTodemo__Result(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTodemo__Result(soap, data), 0) || soap_put_PointerTodemo__Result(soap, data, "demo:Result", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__Result ** SOAP_FMAC4 soap_get_PointerTodemo__Result(struct soap*, struct demo__Result **, const char*, const char*);

#ifndef soap_read_PointerTodemo__Result
#define soap_read_PointerTodemo__Result(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTodemo__Result(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTodemo__AddBResponse
#define SOAP_TYPE_PointerTodemo__AddBResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTodemo__AddBResponse(struct soap*, struct demo__AddBResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTodemo__AddBResponse(struct soap*, const char *, int, struct demo__AddBResponse *const*, const char *);
SOAP_FMAC3 struct demo__AddBResponse ** SOAP_FMAC4 soap_in_PointerTodemo__AddBResponse(struct soap*, const char*, struct demo__AddBResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTodemo__AddBResponse(struct soap*, struct demo__AddBResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTodemo__AddBResponse
#define soap_write_PointerTodemo__AddBResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTodemo__AddBResponse(soap, data), 0) || soap_put_PointerTodemo__AddBResponse(soap, data, "demo:AddBResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct demo__AddBResponse ** SOAP_FMAC4 soap_get_PointerTodemo__AddBResponse(struct soap*, struct demo__AddBResponse **, const char*, const char*);

#ifndef soap_read_PointerTodemo__AddBResponse
#define soap_read_PointerTodemo__AddBResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTodemo__AddBResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
