/* soapServer.cpp
   Generated by gSOAP 2.8.22 from demo.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.22 2015-07-29 03:45:04 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "demo:AddA"))
		return soap_serve_demo__AddA(soap);
	if (!soap_match_tag(soap, soap->tag, "demo:AddB"))
		return soap_serve_demo__AddB(soap);
	if (!soap_match_tag(soap, soap->tag, "demo:AddC"))
		return soap_serve_demo__AddC(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_demo__AddA(struct soap *soap)
{	struct demo__AddA soap_tmp_demo__AddA;
	struct demo__AddAResponse soap_tmp_demo__AddAResponse;
	soap_default_demo__AddAResponse(soap, &soap_tmp_demo__AddAResponse);
	soap_default_demo__AddA(soap, &soap_tmp_demo__AddA);
	if (!soap_get_demo__AddA(soap, &soap_tmp_demo__AddA, "demo:AddA", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = demo__AddA(soap, soap_tmp_demo__AddA.a, soap_tmp_demo__AddA.b, soap_tmp_demo__AddAResponse.res);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_demo__AddAResponse(soap, &soap_tmp_demo__AddAResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_demo__AddAResponse(soap, &soap_tmp_demo__AddAResponse, "demo:AddAResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_demo__AddAResponse(soap, &soap_tmp_demo__AddAResponse, "demo:AddAResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_demo__AddB(struct soap *soap)
{	struct demo__AddB soap_tmp_demo__AddB;
	struct demo__AddBResponse out;
	soap_default_demo__AddBResponse(soap, &out);
	soap_default_demo__AddB(soap, &soap_tmp_demo__AddB);
	if (!soap_get_demo__AddB(soap, &soap_tmp_demo__AddB, "demo:AddB", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = demo__AddB(soap, soap_tmp_demo__AddB.a, soap_tmp_demo__AddB.b, &out);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_demo__AddBResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_demo__AddBResponse(soap, &out, "demo:AddBResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_demo__AddBResponse(soap, &out, "demo:AddBResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_demo__AddC(struct soap *soap)
{	struct demo__AddC soap_tmp_demo__AddC;
	struct demo__Result res;
	soap_default_demo__Result(soap, &res);
	soap_default_demo__AddC(soap, &soap_tmp_demo__AddC);
	if (!soap_get_demo__AddC(soap, &soap_tmp_demo__AddC, "demo:AddC", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = demo__AddC(soap, soap_tmp_demo__AddC._, &res);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_demo__Result(soap, &res);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_demo__Result(soap, &res, "demo:Result", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_demo__Result(soap, &res, "demo:Result", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
